---
name: Release
"on":
    push:

jobs:
    release:
        environment: production
        permissions:
            contents: write
            issues: write
            pull-requests: write
            id-token: write
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Import GPG key
              id: import-gpg
              uses: crazy-max/ghaction-import-gpg@v6
              with:
                  gpg_private_key: "${{ secrets.ARPANREC_GITHUB_ACTIONS_GPG_PRIVATE_KEY }}"
                  passphrase: "${{ secrets.ARPANREC_GITHUB_ACTIONS_GPG_PASSPHRASE }}"
                  git_user_signingkey: true
                  git_commit_gpgsign: true
                  trust_level: 5

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: npm

            - name: Release
              run: |+
                  set -ex
                  git config --global user.email "${{ steps.import-gpg.outputs.email }}"
                  git config --global user.name "${{ steps.import-gpg.outputs.name }}"
                  npx semantic-release@23.0.8 --extends ./.github/files/release.config.cjs
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                  GIT_AUTHOR_NAME: "${{ steps.import-gpg.outputs.name }}"
                  GIT_AUTHOR_EMAIL: "${{ steps.import-gpg.outputs.email }}"
                  GIT_COMMITTER_NAME: "${{ steps.import-gpg.outputs.name }}"
                  GIT_COMMITTER_EMAIL: "${{ steps.import-gpg.outputs.email }}"
